/mnt/nfs/TiMo/scripts/processAsteroid.sh Stevin
/mnt/nfs/TiMo/scripts/processAsteroid.sh Kitt_Peak
/mnt/nfs/TiMo/scripts/processAsteroid.sh Susi
/mnt/nfs/TiMo/scripts/processAsteroid.sh Kn_40
/mnt/nfs/TiMo/scripts/processAsteroid.sh Tangshan
/mnt/nfs/TiMo/scripts/processAsteroid.sh Zvezdara
/mnt/nfs/TiMo/scripts/processAsteroid.sh Clorinde
/mnt/nfs/TiMo/scripts/processAsteroid.sh Abell_30
/mnt/nfs/TiMo/scripts/processAsteroid.sh Sofievka
/mnt/nfs/TiMo/scripts/processAsteroid.sh Fireman
/mnt/nfs/TiMo/scripts/processAsteroid.sh Nansenia
/mnt/nfs/TiMo/scripts/processAsteroid.sh 2001_FO32
/mnt/nfs/TiMo/scripts/processAsteroid.sh Dunham
/mnt/nfs/TiMo/scripts/processAsteroid.sh Shkolnik
/mnt/nfs/TiMo/scripts/processAsteroid.sh Sanborn
/mnt/nfs/TiMo/scripts/processAsteroid.sh Ciardi
/mnt/nfs/TiMo/scripts/processAsteroid.sh van_Belle
/mnt/nfs/TiMo/scripts/processAsteroid.sh Massey
/mnt/nfs/TiMo/scripts/processAsteroid.sh Neugent
/mnt/nfs/TiMo/scripts/processAsteroid.sh Wasserman
/mnt/nfs/TiMo/scripts/processAsteroid.sh Joellama
/mnt/nfs/TiMo/scripts/processAsteroid.sh Jeffhall
/mnt/nfs/TiMo/scripts/processAsteroid.sh Druzhba
